Handle external changes to user
conversation/promos-client pull request #46
Opened 2022-06-01 03:51 UTC by RohanM

We now add user donation details in the user state (https://github.com/conversation/tc/pull/12488).
However, the promos state machine is not notified of this asynchronous change to the user state, and so will stomp those changes if there is a subsequent update.
Add an event handler which will allow TC to notify the promos client of any changes.

2022-06-01 05:24 UTC, nullobject requested changes
It's been a while since I worked on this, but here goes...:smile:

Firstly, mutating the user goes against the functional design of the state machine and could lead to surprises later on.

The state machine should be a pure function: for every event it creates a *new* state, which is stored in local storage (a side effect), and returned as an output.

Keeping it pure could be as simple as:

```js
user = { ...user, foo: 1, bar: 2 }
```

But more importantly, I feel like the `userChange` event doesn't really fit the whole idea behind the state machine. The only thing changing the user should be the state machine itself, in response to things that happened.

For example:

* `visit`: The user visited a page
* `click`: The user clicked on a promo
* `view`: The user saw a promo

The `userChange` event is basically saying "overwrite a bunch of properties in the user state with some new values".

Is there any way we can flip this so that state machine can avoid having to just update a bunch of arbitrary properties? i.e. What was the actual thing that happened?

2022-06-01 05:31 UTC, nullobject commented
@RohanM Thanks for tagging me in this review.

Sorry I haven't been across the recent donations changes, but I don't quite understand why we have a situation where the promos client state machine doesn't know about changes to the user, as it is supposed to be the **single source of truth** for the user state.

The frontend is just meant to tell the promos client about things that happened (through events), and the promos client is the thing that worries about making sure the state is kept up-to-date and persisted to local storage, etc.

2022-06-01 07:32 UTC, RohanM commented on src/stateMachine.js
> +      user = { ...user, donations: event.donations }
Is there anything else we need to do here for the promos to reflect the change to user state?

2022-06-02 00:35 UTC, nullobject approved these changes

2022-06-02 00:35 UTC, merged